name: Test
on:
  push:
    branches: [ main ]
  workflow_dispatch:
jobs:
  check-google:
    runs-on: arc-runner-set
    steps:
      - name: Ping Google
        run: |
          echo "Checking connectivity to google.com..."
          curl -Is https://google.com | head -n 1
